<div class="row">
    <div class="tags">
        <?php foreach ($this->tags as $tag): ?>
            <span class="tagtoggler badge badge-light <?= $tag->isHidden() ? 'hidden' : ''; ?>"
                  data-id="<?= $tag->getId(); ?>"
                  style="background-color: <?= $tag->getColor(); ?>"><?= $tag->getName(); ?></span>
        <?php endforeach; ?>
    </div>
    <?php

    use Chemtool\Doctrine\Entities\Chemical;

    /**
     * @var Chemical $chemical
     */
    foreach ($this->chemicals as $chemical) {
        $appender = '';
        $badges = '';
        foreach ($chemical->getTags() as $tag) {
            $appender .= 'tag_' . $tag->getId() . ' ';
            $appender .= !$tag->isHidden() ? 'tag_' . $tag->getId() . '_active ' : '';
            $badges .= '<span class="badge badge-light" style="background-color: ' . $tag->getColor() . '">' . $tag->getName() . '</span>';
        }

        ?>
        <div class="chemical list-group-item col-sm-2 closed <?= $appender ?>" style="border: thin solid black"
             id="chemical_<?= $chemical->getId() ?>">
            <div class="header"><?= $chemical->getName() != '' ? $chemical->getName() : 'XX__' . $chemical->getIdName(); ?>
                <?= $badges ?>
            </div>
            <div class="content">
                Id=<?= $chemical->getIdName(); ?><br/>
                Name=<?= $chemical->getName(); ?><br/>
                Produced=<?= $chemical->getProduced(); ?><br/>
                Heat-Required=<?= $chemical->getRequireHeat(); ?><br/>
                LCM=<?= $chemical->getLCM(); ?><br/>

                Recipe String:
                <div class="ingredientString">
                    <ul>
                        <?php foreach ($chemical->getRecipe()['string'] as $row): ?>
                            <li><?= $row ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                Ingredients:
                <ul>
                    <?php foreach ($chemical->getParents() as $child):
                        $childChemical = $child->getParentChemical();
                        if (count($childChemical->getParents()) > 0):?>
                            <li>
                                <a data-id="<?= $childChemical->getId() ?>"
                                   href="#chemical_<?= $childChemical->getId() ?>"><?= $childChemical->getName() . ':' . $child->getAmount(); ?></a>
                            </li>
                        <?php else: ?>
                            <li>
                                <?= $childChemical->getName() . ':' . $child->getAmount(); ?>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
                <?php if (count($chemical->getChilds()) > 0): ?>
                    Used In: <a href="javascript:void(0);"
                                onclick="$('#used_id_<?= $chemical->getId() ?>').toggle()">toggle</a>
                    <ul style="display: none" id="used_id_<?= $chemical->getId() ?>">
                        <?php foreach ($chemical->getChilds() as $child):
                            $childChemical = $child->getChemical(); ?>
                            <li>
                                <a data-id="<?= $childChemical->getId() ?>"
                                   href="#chemical_<?= $childChemical->getId() ?>"><?= $childChemical->getName() . ':' . $child->getAmount(); ?></a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
                <a href="<?= $this->url('chemtool', ['action' => 'edit', 'id' => $chemical->getId()]); ?>">edit</a>
            </div>
        </div>
    <?php } ?>
</div>
<a href="<?= $this->url('chemtool', ['action' => 'add', 'id' => 0]); ?>">add</a>