<div class="row">
<?php

use Chemtool\Doctrine\Entities\Chemical;
/**
 * @var Chemical $chemical
 */
foreach ($this->chemicals as $chemical){
    ?>
    <div class="chemical list-group-item col-sm-2" style="border: thin solid black">
        Id=<?=$chemical->getId();?><br />
        Name=<?=$chemical->getName();?><br />
        Idname=<?=$chemical->getIdName();?><br />
        Heat-Required=<?=$chemical->getRequireHeat();?><br />

        Recipe: <ul>
        <?php foreach ($chemical->getParent() as $child):
            $childChemical = $child->getParent();?>
            <li>
                <?=$childChemical->getName().':'.$child->getAmount();?>
            </li>
        <?php endforeach; ?>
        </ul>
        Used In: <ul>
            <?php foreach ($chemical->getChilds() as $child):
                $childChemical = $child->getChemical();?>
                <li>
                    <?=$childChemical->getName().':'.$child->getAmount();?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php }?>
</div>